import type { FeedSource } from '../types';

export const FEED_SOURCES: FeedSource[] = [
  // ══════════════════════════════════════════════════════════════════════
  //  LEFT  (MBFC: Left bias)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'guardian-world',
    name: 'The Guardian',
    url: 'https://www.theguardian.com/world/rss',
    category: 'left',
    region: 'uk',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=theguardian.com&sz=32',
    color: '#052962',
    enabled: true,
    tier: 1,
  },
  {
    id: 'npr-world',
    name: 'NPR',
    url: 'https://feeds.npr.org/1004/rss.xml',
    category: 'left',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=npr.org&sz=32',
    color: '#1A1A2E',
    enabled: true,
    tier: 1,
  },
  {
    id: 'huffpost-world',
    name: 'HuffPost',
    url: 'https://chaski.huffpost.com/us/auto/vertical/world-news',
    category: 'left',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=huffpost.com&sz=32',
    color: '#0dbe3e',
    enabled: true,
    tier: 2,
  },
  {
    id: 'vox-world',
    name: 'Vox',
    url: 'https://www.vox.com/rss/world-politics/index.xml',
    category: 'left',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=vox.com&sz=32',
    color: '#FFF200',
    enabled: true,
    tier: 2,
  },
  {
    id: 'aljazeera',
    name: 'Al Jazeera',
    url: 'https://www.aljazeera.com/xml/rss/all.xml',
    category: 'left',
    region: 'middle-east',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=aljazeera.com&sz=32',
    color: '#FA9000',
    enabled: true,
    tier: 1,
  },
  {
    id: 'the-intercept',
    name: 'The Intercept',
    url: 'https://theintercept.com/feed/?rss',
    category: 'left',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=theintercept.com&sz=32',
    color: '#51D86C',
    enabled: true,
    tier: 3,
  },
  {
    id: 'slate',
    name: 'Slate',
    url: 'https://slate.com/feeds/all.rss',
    category: 'left',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=slate.com&sz=32',
    color: '#262626',
    enabled: true,
    tier: 2,
  },
  {
    id: 'salon',
    name: 'Salon',
    url: 'https://www.salon.com/feed/',
    category: 'left',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=salon.com&sz=32',
    color: '#BC0000',
    enabled: true,
    tier: 3,
  },
  {
    id: 'daily-beast',
    name: 'The Daily Beast',
    url: 'https://feeds.thedailybeast.com/rss/articles',
    category: 'left',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=thedailybeast.com&sz=32',
    color: '#FF0000',
    enabled: true,
    tier: 2,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  LEFT-CENTER  (MBFC: Left-Center bias)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'bbc-news',
    name: 'BBC News',
    url: 'https://feeds.bbci.co.uk/news/rss.xml',
    category: 'left-center',
    region: 'uk',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=bbc.com&sz=32',
    color: '#BB1919',
    enabled: true,
    tier: 1,
  },
  {
    id: 'cnn',
    name: 'CNN',
    url: 'https://rss.cnn.com/rss/edition.rss',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=cnn.com&sz=32',
    color: '#CC0000',
    enabled: true,
    tier: 1,
  },
  {
    id: 'nytimes',
    name: 'The New York Times',
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=nytimes.com&sz=32',
    color: '#1A1A1A',
    enabled: true,
    tier: 1,
  },
  {
    id: 'washpost-world',
    name: 'Washington Post',
    url: 'https://feeds.washingtonpost.com/rss/world',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=washingtonpost.com&sz=32',
    color: '#231F20',
    enabled: true,
    tier: 1,
  },
  {
    id: 'abcnews',
    name: 'ABC News',
    url: 'https://abcnews.go.com/abcnews/internationalheadlines',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=abcnews.go.com&sz=32',
    color: '#0A0A0A',
    enabled: true,
    tier: 2,
  },
  {
    id: 'cbsnews',
    name: 'CBS News',
    url: 'https://www.cbsnews.com/latest/rss/world',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=cbsnews.com&sz=32',
    color: '#1B5BBF',
    enabled: true,
    tier: 2,
  },
  {
    id: 'nbcnews',
    name: 'NBC News',
    url: 'https://feeds.nbcnews.com/nbcnews/public/world',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=nbcnews.com&sz=32',
    color: '#3F48CC',
    enabled: true,
    tier: 2,
  },
  {
    id: 'pbs-newshour',
    name: 'PBS NewsHour',
    url: 'https://www.pbs.org/newshour/feeds/rss/headlines',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=pbs.org&sz=32',
    color: '#2638C4',
    enabled: true,
    tier: 2,
  },
  {
    id: 'politico',
    name: 'Politico',
    url: 'https://www.politico.com/rss/politicopicks.xml',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=politico.com&sz=32',
    color: '#BE1717',
    enabled: true,
    tier: 2,
  },
  {
    id: 'time',
    name: 'TIME',
    url: 'https://time.com/feed/',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=time.com&sz=32',
    color: '#E90606',
    enabled: true,
    tier: 2,
  },
  {
    id: 'the-atlantic',
    name: 'The Atlantic',
    url: 'https://www.theatlantic.com/feed/all/',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=theatlantic.com&sz=32',
    color: '#C62828',
    enabled: true,
    tier: 2,
  },
  {
    id: 'propublica',
    name: 'ProPublica',
    url: 'https://www.propublica.org/feeds/propublica/main',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=propublica.org&sz=32',
    color: '#181818',
    enabled: true,
    tier: 2,
  },
  {
    id: 'usa-today',
    name: 'USA Today',
    url: 'https://rss.usatoday.com/UsatodaycomNation-TopStories',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=usatoday.com&sz=32',
    color: '#009BFF',
    enabled: true,
    tier: 2,
  },
  {
    id: 'la-times',
    name: 'Los Angeles Times',
    url: 'https://www.latimes.com/world-nation/rss2.0.xml',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=latimes.com&sz=32',
    color: '#000000',
    enabled: true,
    tier: 2,
  },
  {
    id: 'business-insider',
    name: 'Business Insider',
    url: 'https://feeds.businessinsider.com/custom/all',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=businessinsider.com&sz=32',
    color: '#0F6AB0',
    enabled: true,
    tier: 2,
  },
  {
    id: 'cnbc',
    name: 'CNBC',
    url: 'https://www.cnbc.com/id/100003114/device/rss/rss.html',
    category: 'left-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=cnbc.com&sz=32',
    color: '#005594',
    enabled: true,
    tier: 2,
  },
  {
    id: 'cbc-news',
    name: 'CBC News',
    url: 'https://www.cbc.ca/webfeed/rss/rss-topstories',
    category: 'left-center',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=cbc.ca&sz=32',
    color: '#E02826',
    enabled: true,
    tier: 2,
  },
  {
    id: 'independent',
    name: 'The Independent',
    url: 'https://www.independent.co.uk/news/world/rss',
    category: 'left-center',
    region: 'uk',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=independent.co.uk&sz=32',
    color: '#EC1A2E',
    enabled: true,
    tier: 2,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  CENTER  (MBFC: Least Biased)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'reuters',
    name: 'Reuters',
    url: 'https://www.reutersagency.com/feed/?taxonomy=best-sectors&post_type=best',
    category: 'center',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=reuters.com&sz=32',
    color: '#FF8000',
    enabled: true,
    tier: 1,
  },
  {
    id: 'ap-news',
    name: 'AP News',
    url: 'https://rsshub.app/apnews/topics/apf-topnews',
    category: 'center',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=apnews.com&sz=32',
    color: '#EF3E42',
    enabled: true,
    tier: 1,
  },
  {
    id: 'the-hill',
    name: 'The Hill',
    url: 'https://thehill.com/homenews/feed/',
    category: 'center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=thehill.com&sz=32',
    color: '#0074C1',
    enabled: true,
    tier: 2,
  },
  {
    id: 'the-economist',
    name: 'The Economist',
    url: 'https://www.economist.com/latest/rss.xml',
    category: 'center',
    region: 'uk',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=economist.com&sz=32',
    color: '#E3120B',
    enabled: true,
    tier: 2,
  },
  {
    id: 'newsweek',
    name: 'Newsweek',
    url: 'https://www.newsweek.com/rss',
    category: 'center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=newsweek.com&sz=32',
    color: '#C4000A',
    enabled: true,
    tier: 2,
  },
  {
    id: 'axios',
    name: 'Axios',
    url: 'https://api.axios.com/feed/',
    category: 'center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=axios.com&sz=32',
    color: '#3562FF',
    enabled: true,
    tier: 2,
  },
  {
    id: 'un-news',
    name: 'UN News',
    url: 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
    category: 'center',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=news.un.org&sz=32',
    color: '#009EDB',
    enabled: true,
    tier: 2,
  },
  {
    id: 'forbes',
    name: 'Forbes',
    url: 'https://www.forbes.com/real-time/feed2/',
    category: 'center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=forbes.com&sz=32',
    color: '#0F0F0F',
    enabled: true,
    tier: 2,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  RIGHT-CENTER  (MBFC: Right-Center bias)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'fox-news',
    name: 'Fox News',
    url: 'https://moxie.foxnews.com/google-publisher/latest.xml',
    category: 'right-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=foxnews.com&sz=32',
    color: '#003366',
    enabled: true,
    tier: 1,
  },
  {
    id: 'wsj',
    name: 'Wall Street Journal',
    url: 'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
    category: 'right-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=wsj.com&sz=32',
    color: '#0274B6',
    enabled: true,
    tier: 1,
  },
  {
    id: 'telegraph',
    name: 'The Telegraph',
    url: 'https://www.telegraph.co.uk/news/rss.xml',
    category: 'right-center',
    region: 'uk',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=telegraph.co.uk&sz=32',
    color: '#231F20',
    enabled: true,
    tier: 2,
  },
  {
    id: 'nypost',
    name: 'New York Post',
    url: 'https://nypost.com/feed/',
    category: 'right-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=nypost.com&sz=32',
    color: '#C41200',
    enabled: true,
    tier: 2,
  },
  {
    id: 'daily-mail',
    name: 'Daily Mail',
    url: 'https://www.dailymail.co.uk/articles.rss',
    category: 'right-center',
    region: 'uk',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=dailymail.co.uk&sz=32',
    color: '#004DB3',
    enabled: true,
    tier: 2,
  },
  {
    id: 'reason',
    name: 'Reason',
    url: 'https://reason.com/feed/',
    category: 'right-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=reason.com&sz=32',
    color: '#6B6B6B',
    enabled: true,
    tier: 2,
  },
  {
    id: 'washington-examiner',
    name: 'Washington Examiner',
    url: 'https://www.washingtonexaminer.com/feed',
    category: 'right-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=washingtonexaminer.com&sz=32',
    color: '#C8102E',
    enabled: true,
    tier: 2,
  },
  {
    id: 'washington-times',
    name: 'Washington Times',
    url: 'https://www.washingtontimes.com/rss/headlines/news/',
    category: 'right-center',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=washingtontimes.com&sz=32',
    color: '#000066',
    enabled: true,
    tier: 2,
  },
  {
    id: 'national-post',
    name: 'National Post',
    url: 'https://nationalpost.com/feed',
    category: 'right-center',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=nationalpost.com&sz=32',
    color: '#CE0000',
    enabled: true,
    tier: 3,
  },
  {
    id: 'the-spectator',
    name: 'The Spectator',
    url: 'https://www.spectator.co.uk/feed/',
    category: 'right-center',
    region: 'uk',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=spectator.co.uk&sz=32',
    color: '#004E3F',
    enabled: true,
    tier: 3,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  RIGHT  (MBFC: Right bias)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'breitbart',
    name: 'Breitbart',
    url: 'https://feeds.feedburner.com/breitbart',
    category: 'right',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=breitbart.com&sz=32',
    color: '#F38321',
    enabled: true,
    tier: 2,
  },
  {
    id: 'daily-wire',
    name: 'The Daily Wire',
    url: 'https://www.dailywire.com/feeds/rss.xml',
    category: 'right',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=dailywire.com&sz=32',
    color: '#F4511E',
    enabled: true,
    tier: 3,
  },
  {
    id: 'national-review',
    name: 'National Review',
    url: 'https://www.nationalreview.com/feed/',
    category: 'right',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=nationalreview.com&sz=32',
    color: '#00427F',
    enabled: true,
    tier: 2,
  },
  {
    id: 'american-conservative',
    name: 'The American Conservative',
    url: 'https://www.theamericanconservative.com/feed/',
    category: 'right',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=theamericanconservative.com&sz=32',
    color: '#1B3A5C',
    enabled: true,
    tier: 2,
  },
  {
    id: 'the-federalist',
    name: 'The Federalist',
    url: 'https://thefederalist.com/feed/',
    category: 'right',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=thefederalist.com&sz=32',
    color: '#1A1A1A',
    enabled: true,
    tier: 3,
  },
  {
    id: 'epoch-times',
    name: 'The Epoch Times',
    url: 'https://www.theepochtimes.com/c-us/feed',
    category: 'right',
    region: 'us',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=theepochtimes.com&sz=32',
    color: '#22409A',
    enabled: true,
    tier: 3,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  INTERNATIONAL — EUROPE
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'dw',
    name: 'DW (Deutsche Welle)',
    url: 'https://rss.dw.com/rdf/rss-en-all',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=dw.com&sz=32',
    color: '#0080C8',
    enabled: true,
    tier: 1,
  },
  {
    id: 'france24',
    name: 'France24',
    url: 'https://www.france24.com/en/rss',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=france24.com&sz=32',
    color: '#00A0E3',
    enabled: true,
    tier: 2,
  },
  {
    id: 'sky-news',
    name: 'Sky News',
    url: 'https://feeds.skynews.com/feeds/rss/world.xml',
    category: 'independent',
    region: 'uk',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=news.sky.com&sz=32',
    color: '#9B0000',
    enabled: true,
    tier: 2,
  },
  {
    id: 'rte',
    name: 'RTÉ (Ireland)',
    url: 'https://www.rte.ie/news/rss/news-headlines.xml',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=rte.ie&sz=32',
    color: '#3166AF',
    enabled: true,
    tier: 2,
  },
  {
    id: 'irish-times',
    name: 'The Irish Times',
    url: 'https://www.irishtimes.com/cmlink/the-irish-times-news-1.1319192',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=irishtimes.com&sz=32',
    color: '#0C3048',
    enabled: true,
    tier: 2,
  },
  {
    id: 'euronews',
    name: 'Euronews',
    url: 'https://www.euronews.com/rss',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=euronews.com&sz=32',
    color: '#003C71',
    enabled: true,
    tier: 2,
  },
  {
    id: 'politico-eu',
    name: 'Politico Europe',
    url: 'https://www.politico.eu/feed/',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=politico.eu&sz=32',
    color: '#BE1717',
    enabled: true,
    tier: 2,
  },
  {
    id: 'swissinfo',
    name: 'SWI swissinfo.ch',
    url: 'https://www.swissinfo.ch/eng/top-news/rss',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=swissinfo.ch&sz=32',
    color: '#E30613',
    enabled: true,
    tier: 2,
  },
  {
    id: 'spiegel-intl',
    name: 'Der Spiegel',
    url: 'https://www.spiegel.de/international/index.rss',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=spiegel.de&sz=32',
    color: '#E64415',
    enabled: true,
    tier: 2,
  },
  {
    id: 'moscow-times',
    name: 'The Moscow Times',
    url: 'https://www.themoscowtimes.com/rss/news',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=themoscowtimes.com&sz=32',
    color: '#8B0000',
    enabled: true,
    tier: 2,
  },
  {
    id: 'euractiv',
    name: 'Euractiv',
    url: 'https://www.euractiv.com/feed/',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=euractiv.com&sz=32',
    color: '#003399',
    enabled: true,
    tier: 3,
  },
  {
    id: 'ansa-english',
    name: 'ANSA (Italy)',
    url: 'https://www.ansa.it/english/news/rss.xml',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=ansa.it&sz=32',
    color: '#003DA5',
    enabled: true,
    tier: 2,
  },
  {
    id: 'ekathimerini',
    name: 'Ekathimerini (Greece)',
    url: 'https://www.ekathimerini.com/rss',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=ekathimerini.com&sz=32',
    color: '#1A237E',
    enabled: true,
    tier: 3,
  },
  {
    id: 'balkan-insight',
    name: 'Balkan Insight',
    url: 'https://balkaninsight.com/feed/',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=balkaninsight.com&sz=32',
    color: '#2C3E50',
    enabled: true,
    tier: 3,
  },
  {
    id: 'radio-poland',
    name: 'Radio Poland',
    url: 'https://www.thenews.pl/rss',
    category: 'independent',
    region: 'eu',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=thenews.pl&sz=32',
    color: '#DC143C',
    enabled: true,
    tier: 3,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  INTERNATIONAL — MIDDLE EAST
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'arab-news',
    name: 'Arab News',
    url: 'https://www.arabnews.com/rss.xml',
    category: 'independent',
    region: 'middle-east',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=arabnews.com&sz=32',
    color: '#1F4091',
    enabled: true,
    tier: 2,
  },
  {
    id: 'jerusalem-post',
    name: 'The Jerusalem Post',
    url: 'https://www.jpost.com/rss/rssfeedsfrontpage.aspx',
    category: 'independent',
    region: 'middle-east',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=jpost.com&sz=32',
    color: '#003B71',
    enabled: true,
    tier: 2,
  },
  {
    id: 'middle-east-eye',
    name: 'Middle East Eye',
    url: 'https://www.middleeasteye.net/rss',
    category: 'independent',
    region: 'middle-east',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=middleeasteye.net&sz=32',
    color: '#000000',
    enabled: true,
    tier: 2,
  },
  {
    id: 'trt-world',
    name: 'TRT World',
    url: 'https://www.trtworld.com/rss',
    category: 'independent',
    region: 'middle-east',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=trtworld.com&sz=32',
    color: '#BF1E2D',
    enabled: true,
    tier: 2,
  },
  {
    id: 'gulf-news',
    name: 'Gulf News',
    url: 'https://gulfnews.com/rss',
    category: 'independent',
    region: 'middle-east',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=gulfnews.com&sz=32',
    color: '#003E7E',
    enabled: true,
    tier: 2,
  },
  {
    id: 'daily-sabah',
    name: 'Daily Sabah',
    url: 'https://www.dailysabah.com/rssFeed/todays-headlines',
    category: 'independent',
    region: 'middle-east',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=dailysabah.com&sz=32',
    color: '#1B2838',
    enabled: true,
    tier: 3,
  },
  {
    id: 'anadolu-agency',
    name: 'Anadolu Agency',
    url: 'https://www.aa.com.tr/en/rss/default?cat=world',
    category: 'independent',
    region: 'middle-east',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=aa.com.tr&sz=32',
    color: '#C8102E',
    enabled: true,
    tier: 2,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  INTERNATIONAL — ASIA-PACIFIC
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'times-of-india',
    name: 'Times of India',
    url: 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=timesofindia.indiatimes.com&sz=32',
    color: '#E42529',
    enabled: true,
    tier: 2,
  },
  {
    id: 'scmp',
    name: 'South China Morning Post',
    url: 'https://www.scmp.com/rss/91/feed',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=scmp.com&sz=32',
    color: '#FFCC32',
    enabled: true,
    tier: 2,
  },
  {
    id: 'nhk-world',
    name: 'NHK World',
    url: 'https://www3.nhk.or.jp/rss/news/cat0.xml',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=nhk.or.jp&sz=32',
    color: '#026CB5',
    enabled: true,
    tier: 2,
  },
  {
    id: 'channel-news-asia',
    name: 'Channel News Asia',
    url: 'https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=channelnewsasia.com&sz=32',
    color: '#C8102E',
    enabled: true,
    tier: 2,
  },
  {
    id: 'the-hindu',
    name: 'The Hindu',
    url: 'https://www.thehindu.com/news/national/feeder/default.rss',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=thehindu.com&sz=32',
    color: '#0A3068',
    enabled: true,
    tier: 2,
  },
  {
    id: 'ndtv',
    name: 'NDTV',
    url: 'https://feeds.feedburner.com/ndtvnews-top-stories',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=ndtv.com&sz=32',
    color: '#E23838',
    enabled: true,
    tier: 2,
  },
  {
    id: 'hindustan-times',
    name: 'Hindustan Times',
    url: 'https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=hindustantimes.com&sz=32',
    color: '#076DB1',
    enabled: true,
    tier: 2,
  },
  {
    id: 'indian-express',
    name: 'The Indian Express',
    url: 'https://indianexpress.com/feed/',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=indianexpress.com&sz=32',
    color: '#C62828',
    enabled: true,
    tier: 2,
  },
  {
    id: 'the-wire-india',
    name: 'The Wire',
    url: 'https://thewire.in/feed',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=thewire.in&sz=32',
    color: '#262626',
    enabled: true,
    tier: 3,
  },
  {
    id: 'scroll-india',
    name: 'Scroll.in',
    url: 'https://scroll.in/feed',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=scroll.in&sz=32',
    color: '#D32F2F',
    enabled: true,
    tier: 3,
  },
  {
    id: 'india-today',
    name: 'India Today',
    url: 'https://www.indiatoday.in/rss/home',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=indiatoday.in&sz=32',
    color: '#E11E28',
    enabled: true,
    tier: 3,
  },
  {
    id: 'dawn',
    name: 'Dawn',
    url: 'https://www.dawn.com/feeds/home',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=dawn.com&sz=32',
    color: '#237848',
    enabled: true,
    tier: 2,
  },
  {
    id: 'japan-times',
    name: 'The Japan Times',
    url: 'https://www.japantimes.co.jp/feed/',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=japantimes.co.jp&sz=32',
    color: '#BC2A26',
    enabled: true,
    tier: 2,
  },
  {
    id: 'korea-herald',
    name: 'The Korea Herald',
    url: 'https://www.koreaherald.com/common/rss_xml.php?ct=102',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=koreaherald.com&sz=32',
    color: '#0054A6',
    enabled: true,
    tier: 2,
  },
  {
    id: 'bangkok-post',
    name: 'Bangkok Post',
    url: 'https://www.bangkokpost.com/rss/data/topstories.xml',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=bangkokpost.com&sz=32',
    color: '#1A3C6E',
    enabled: true,
    tier: 2,
  },
  {
    id: 'the-diplomat',
    name: 'The Diplomat',
    url: 'https://thediplomat.com/feed/',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=thediplomat.com&sz=32',
    color: '#0F4C75',
    enabled: true,
    tier: 2,
  },
  {
    id: 'taipei-times',
    name: 'Taipei Times',
    url: 'https://www.taipeitimes.com/xml/index.rss',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=taipeitimes.com&sz=32',
    color: '#003399',
    enabled: true,
    tier: 3,
  },
  {
    id: 'rappler',
    name: 'Rappler',
    url: 'https://www.rappler.com/feed/',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=rappler.com&sz=32',
    color: '#4267B2',
    enabled: true,
    tier: 2,
  },
  {
    id: 'vnexpress',
    name: 'VnExpress International',
    url: 'https://e.vnexpress.net/rss/news.rss',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=vnexpress.net&sz=32',
    color: '#B80000',
    enabled: true,
    tier: 3,
  },
  {
    id: 'asia-times',
    name: 'Asia Times',
    url: 'https://asiatimes.com/feed/',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=asiatimes.com&sz=32',
    color: '#8B0000',
    enabled: true,
    tier: 2,
  },
  {
    id: 'daily-star-bd',
    name: 'The Daily Star (Bangladesh)',
    url: 'https://www.thedailystar.net/frontpage/rss.xml',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=thedailystar.net&sz=32',
    color: '#003B8E',
    enabled: true,
    tier: 3,
  },
  {
    id: 'the-star-malaysia',
    name: 'The Star (Malaysia)',
    url: 'https://www.thestar.com.my/rss/News',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=thestar.com.my&sz=32',
    color: '#C91D1D',
    enabled: true,
    tier: 3,
  },
  {
    id: 'east-asia-forum',
    name: 'East Asia Forum',
    url: 'https://www.eastasiaforum.org/feed/',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=eastasiaforum.org&sz=32',
    color: '#004080',
    enabled: true,
    tier: 3,
  },
  {
    id: 'xinhua',
    name: 'Xinhua News',
    url: 'https://www.xinhuanet.com/english/rss/worldrss.xml',
    category: 'independent',
    region: 'asia',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=xinhuanet.com&sz=32',
    color: '#CC0000',
    enabled: true,
    tier: 3,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  INTERNATIONAL — AFRICA
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'news24',
    name: 'News24',
    url: 'https://feeds.news24.com/articles/news24/TopStories/rss',
    category: 'independent',
    region: 'africa',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=news24.com&sz=32',
    color: '#EC1C24',
    enabled: true,
    tier: 2,
  },
  {
    id: 'daily-maverick',
    name: 'Daily Maverick',
    url: 'https://www.dailymaverick.co.za/feed/',
    category: 'independent',
    region: 'africa',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=dailymaverick.co.za&sz=32',
    color: '#DD2226',
    enabled: true,
    tier: 2,
  },
  {
    id: 'allafrica',
    name: 'AllAfrica',
    url: 'https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf',
    category: 'independent',
    region: 'africa',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=allafrica.com&sz=32',
    color: '#003E7E',
    enabled: true,
    tier: 2,
  },
  {
    id: 'premium-times',
    name: 'Premium Times (Nigeria)',
    url: 'https://www.premiumtimesng.com/feed',
    category: 'independent',
    region: 'africa',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=premiumtimesng.com&sz=32',
    color: '#0B3D91',
    enabled: true,
    tier: 2,
  },
  {
    id: 'punch-ng',
    name: 'Punch (Nigeria)',
    url: 'https://punchng.com/feed/',
    category: 'independent',
    region: 'africa',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=punchng.com&sz=32',
    color: '#003399',
    enabled: true,
    tier: 3,
  },
  {
    id: 'the-east-african',
    name: 'The East African',
    url: 'https://www.theeastafrican.co.ke/tea/rss',
    category: 'independent',
    region: 'africa',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=theeastafrican.co.ke&sz=32',
    color: '#C62828',
    enabled: true,
    tier: 2,
  },
  {
    id: 'nation-africa',
    name: 'Nation Africa (Kenya)',
    url: 'https://nation.africa/kenya/rss',
    category: 'independent',
    region: 'africa',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=nation.africa&sz=32',
    color: '#004D99',
    enabled: true,
    tier: 3,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  INTERNATIONAL — OCEANIA
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'abc-australia',
    name: 'ABC Australia',
    url: 'https://www.abc.net.au/news/feed/2942460/rss.xml',
    category: 'independent',
    region: 'oceania',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=abc.net.au&sz=32',
    color: '#000000',
    enabled: true,
    tier: 2,
  },
  {
    id: 'nz-herald',
    name: 'New Zealand Herald',
    url: 'https://www.nzherald.co.nz/arc/outboundfeeds/rss/curated/78/?outputType=xml',
    category: 'independent',
    region: 'oceania',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=nzherald.co.nz&sz=32',
    color: '#005D8F',
    enabled: true,
    tier: 2,
  },
  {
    id: 'rnz',
    name: 'RNZ',
    url: 'https://www.rnz.co.nz/rss/national.xml',
    category: 'independent',
    region: 'oceania',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=rnz.co.nz&sz=32',
    color: '#1C6EA4',
    enabled: true,
    tier: 2,
  },
  {
    id: 'smh',
    name: 'Sydney Morning Herald',
    url: 'https://www.smh.com.au/rss/feed.xml',
    category: 'independent',
    region: 'oceania',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=smh.com.au&sz=32',
    color: '#263238',
    enabled: true,
    tier: 2,
  },
  {
    id: 'sbs-australia',
    name: 'SBS News',
    url: 'https://www.sbs.com.au/news/feed',
    category: 'independent',
    region: 'oceania',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=sbs.com.au&sz=32',
    color: '#FF5A00',
    enabled: true,
    tier: 2,
  },
  {
    id: 'stuff-nz',
    name: 'Stuff (New Zealand)',
    url: 'https://www.stuff.co.nz/rss',
    category: 'independent',
    region: 'oceania',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=stuff.co.nz&sz=32',
    color: '#E91C24',
    enabled: true,
    tier: 3,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  INTERNATIONAL — LATIN AMERICA & CARIBBEAN
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'mercopress',
    name: 'MercoPress',
    url: 'https://en.mercopress.com/rss',
    category: 'independent',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=mercopress.com&sz=32',
    color: '#003DA5',
    enabled: true,
    tier: 2,
  },
  {
    id: 'buenos-aires-times',
    name: 'Buenos Aires Times',
    url: 'https://www.batimes.com.ar/feed',
    category: 'independent',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=batimes.com.ar&sz=32',
    color: '#1A3C6E',
    enabled: true,
    tier: 3,
  },
  {
    id: 'tico-times',
    name: 'The Tico Times',
    url: 'https://ticotimes.net/feed',
    category: 'independent',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=ticotimes.net&sz=32',
    color: '#00693E',
    enabled: true,
    tier: 3,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  INTERNATIONAL — GLOBAL / WIRE SERVICES
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'the-conversation',
    name: 'The Conversation',
    url: 'https://theconversation.com/us/articles.atom',
    category: 'independent',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=theconversation.com&sz=32',
    color: '#D8352A',
    enabled: true,
    tier: 3,
  },
  {
    id: 'globe-and-mail',
    name: 'The Globe and Mail',
    url: 'https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/world/',
    category: 'independent',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=theglobeandmail.com&sz=32',
    color: '#1F3C50',
    enabled: true,
    tier: 3,
  },
  {
    id: 'tass',
    name: 'TASS',
    url: 'https://tass.com/rss/v2.xml',
    category: 'independent',
    region: 'global',
    language: 'en',
    icon: 'https://www.google.com/s2/favicons?domain=tass.com&sz=32',
    color: '#003DA5',
    enabled: true,
    tier: 3,
  },
];

export function getEnabledFeeds(customEnabled?: Record<string, boolean>): FeedSource[] {
  return FEED_SOURCES.filter(f => {
    if (customEnabled && f.id in customEnabled) return customEnabled[f.id];
    return f.enabled;
  });
}

export function getFeedsByTier(feeds: FeedSource[]): [FeedSource[], FeedSource[], FeedSource[]] {
  return [
    feeds.filter(f => f.tier === 1),
    feeds.filter(f => f.tier === 2),
    feeds.filter(f => f.tier === 3),
  ];
}
